import React, { useEffect, useMemo, useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  AlertCircle,
  Archive,
  BarChart3,
  BookMarked,
  BookOpen,
  Calendar,
  CheckCircle,
  Circle,
  Clock3,
  Edit2,
  FileDown,
  FileText,
  Layers3,
  Moon,
  Package,
  PenTool,
  Plus,
  Save,
  Search,
  Sparkles,
  Trash2,
  X,
